sequenceDiagram
  participant participant_runAsync as runAsync
  participant participant_runCheckedProcessAsync as runCheckedProcessAsync
  participant participant_runDeploymentHookAsync as runDeploymentHookAsync
  participant participant_runProcessAsync as runProcessAsync
  participant_runDeploymentHookAsync->>participant_runAsync: hook.runAsync()
  participant_runAsync->>participant_runCheckedProcessAsync: runCheckedProcessAsync()
  participant_runCheckedProcessAsync->>participant_runProcessAsync: runProcessAsync()
  participant_runProcessAsync-->>participant_runCheckedProcessAsync: return
  participant_runCheckedProcessAsync-->>participant_runAsync: return
  participant_runAsync-->>participant_runDeploymentHookAsync: return
