export const CERTBOT_IMAGE = 'certbot/certbot:v5.8.0';
export const CERTBOT_DEFAULT_STORAGE_DIRECTORY = '.ankh-tls';
export const CERTBOT_CONTAINER_ROOT = '/data';
export const CERTBOT_CONTAINER_WEBROOT = `${CERTBOT_CONTAINER_ROOT}/webroot`;
export const CERTBOT_CONTAINER_CONFIG_DIR = `${CERTBOT_CONTAINER_ROOT}/config`;
export const CERTBOT_CONTAINER_WORK_DIR = `${CERTBOT_CONTAINER_ROOT}/work`;
export const CERTBOT_CONTAINER_LOGS_DIR = `${CERTBOT_CONTAINER_ROOT}/logs`;
